Repository boostcampwm-2024/web10-QuizGround, pull requests merged in 2024-12, with the labels that each got.

#297 [BE] fix# 채점 오류 해결 및 TTL 관리 삭제
  BE/src/game/redis/game-redis-memory.service.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.room.service.ts
Labels: bug

#298 [BE] fix-room-clean
  BE/src/game/redis/game-redis-memory.service.ts
  BE/src/game/redis/subscribers/room.cleanup.subscriber.ts
  BE/src/game/service/game.room.service.ts
Labels: bug

#303 [BE] fix: updatePosition 성능개선
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/service/game.service.ts
  BE/src/game/validations/game.validator.ts
Labels: enhancement

#304 [BE] fix# 순위 오류, 옵션 오류, 재접속 오류 수정
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.room.service.ts
Labels: bug

#310 [BE] fix# 게임 종료 후 새로운 호스트 아이디 오류 수정
  BE/src/game/game.gateway.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
Labels: bug

#319 [FE] fix: 대기방 새로고침 기능 수정
  FE/src/features/lobby/GameLobbyPage.tsx
  FE/src/features/lobby/LobbyList.tsx
Labels: 3. 대기방 구현

#323 [BE] hotfix#테스트용 api 삭제, fix db test
  BE/src/InitDB/InitDB.controller.ts
  BE/test/integration/quiz-set/quiz.integration.spec.ts
Labels: bug

#334 [BE] feat#333 updatePos socket batch 처리
  BE/src/game/redis/subscribers/player.subscriber.ts
Labels: 1. 게임방 구현

#330 [BE] feat#329 퀴즈검색 성능개선
  BE/src/InitDB/QUIZ_SET_TEST_DATA.ts
  BE/src/main.ts
  BE/src/quiz-set/entities/quiz-choice.entity.ts
  BE/src/quiz-set/entities/quiz-set.entity.ts
  BE/src/quiz-set/entities/quiz.entity.ts
  BE/src/quiz-set/quiz-set.controller.ts
  BE/src/quiz-set/service/quiz-set-read.service.ts
  docs/db.MD
Labels: 6. 퀴즈셋 생성 구현

#338 [BE] feat#333 배치기능 모듈화
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/service/BatchProcessor.ts
  BE/src/game/service/game.chat.service.ts
Labels: 1. 게임방 구현
