Repository boostcampwm-2024/web10-QuizGround, pull requests merged in 2024-11, with the labels that each got.

#161 Docs: PR_template 올바르게 수정
  .github/pull_request_template.md
Labels: 기타

#160 [FE] feat#155-157 메인 페이지 및 게임 생성 페이지 구현
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/api/socket.ts
  FE/src/constants/socketEvents.ts
  FE/src/main.tsx
  FE/src/pages/GameSetupPage.tsx
  FE/src/pages/MainPage.tsx
  FE/tailwind.config.js
Labels: 4. 게임방 생성 구현

#158 [BE] feat#33 WebSocketGateway 설정 및 게임방 생성 기능 구현 (테스트 포함)
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/filters/ws-exception.filter.ts
  BE/src/game/dto/create-game.dto.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/test/game.e2e-spec.ts
Labels: 4. 게임방 생성 구현

#159 [BE] feat#156 자동배포 구현
  .github/workflows/deploy.yml
  BE/src/app.controller.spec.ts
  BE/src/app.service.ts
Labels: 0. 개발 환경 세팅

#165 [FE] feat#15#16#31#41#162 플레이어 닉네임 입력창 및 게임 대기방 레이아웃 개발
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/api/socket.ts
  FE/src/components/Chat.tsx
  FE/src/components/ClipboardCopy.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/HeaderBar.tsx
  FE/src/components/Modal.tsx
  FE/src/components/ParticipantDisplay.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/components/QuizView.tsx
  FE/src/constants/roomConfig.ts
  FE/src/index.css
  FE/src/pages/GamePage.tsx
  FE/src/pages/GameSetupPage.tsx
  FE/tailwind.config.js
  FE/tsconfig.app.json
  FE/tsconfig.node.json
  FE/vite.config.ts
Labels: 3. 대기방 구현

#172 [FE] feat#16#20
  FE/package.json
  FE/src/App.tsx
  FE/src/api/socket.ts
  FE/src/api/socketEventTypes.ts
  FE/src/components/Chat.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/ParticipantDisplay.tsx
  FE/src/components/Player.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/pages/GamePage.tsx
  FE/src/pages/GameSetupPage.tsx
  FE/src/store/useChatStore.ts
  FE/src/store/usePlayerStore.ts
  FE/src/store/useRoomStore.ts
Labels: 1. 게임방 구현, 3. 대기방 구현

#171 [BE] feat#19 updatePosition API 구현, 리팩토링
  .github/workflows/deploy.yml
  BE/.jest-test-results.json
  BE/src/app.controller.spec.ts
  BE/src/app.module.ts
  BE/src/common/constants/socket-events.ts
  BE/src/common/filters/ws-exception.filter.ts
  BE/src/common/utils/utils.spec.ts
  BE/src/game/dto/create-game.dto.ts
  BE/src/game/dto/update-position.dto.ts
  BE/src/game/game.gateway.spec.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/main.ts
  BE/test/game.e2e-spec.ts
Labels: 1. 게임방 구현

#183 [FE] feat#22#139#141#180#181 플레이어 이동, 채팅 스크롤, 페이지 UI 변경
  FE/index.html
  FE/public/icon.png
  FE/src/api/socket.ts
  FE/src/api/socketEventTypes.ts
  FE/src/components/Chat.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/HeaderBar.tsx
  FE/src/components/ParticipantDisplay.tsx
  FE/src/components/Player.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/constants/roomConfig.ts
  FE/src/pages/GameSetupPage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/store/usePlayerStore.ts
Labels: 1. 게임방 구현, 4. 게임방 생성 구현

#185 [BE] feat#179#178 redis 설정, startGame 구현
  BE/package-lock.json
  BE/package.json
  BE/src/game/decorators/validate-room.decorator.ts
  BE/src/game/dto/start-game.dto.ts
  BE/src/game/dto/update-position.dto.ts
  BE/src/game/game.gateway.ts
  BE/src/main.ts
  BE/src/repository/RedisClient.ts
  BE/test/game.e2e-spec.ts
Labels: 0. 개발 환경 세팅

#188 [BE] feat#140,#25 exitRoom 전송, host 퇴장 시 변경
  BE/package-lock.json
  BE/src/game/game.gateway.ts
Labels: 1. 게임방 구현

#187 [FE] feat#59#44-46 퀴즈 생성 및 조회 레이아웃 개발
  FE/src/App.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/QuizSettingModal.tsx
  FE/src/components/QuizView.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/QuizSetupPage.tsx
Labels: 3. 대기방 구현, 6. 퀴즈셋 생성 구현

#189 [BE] feat#47#179 퀴즈셋 API 구현
  BE/.gitignore
  BE/package-lock.json
  BE/src/InitDB/InitDB.Service.ts
  BE/src/InitDB/InitDB.controller.ts
  BE/src/InitDB/InitDB.module.ts
  BE/src/InitDB/QUIZ_SET_TEST_DATA.ts
  BE/src/app.module.ts
  BE/src/common/entity/base.entity.ts
  BE/src/quiz/dto/Response.dto.ts
  BE/src/quiz/dto/create-quiz.dto.ts
  BE/src/quiz/dto/update-quiz.dto.ts
  BE/src/quiz/entities/quiz-choice.entity.ts
  BE/src/quiz/entities/quiz-set.entity.ts
  BE/src/quiz/entities/quiz.entity.ts
  BE/src/quiz/quiz.controller.spec.ts
  BE/src/quiz/quiz.controller.ts
  BE/src/quiz/quiz.module.ts
  BE/src/quiz/quiz.service.spec.ts
  BE/src/quiz/quiz.service.ts
  BE/src/user/dto/create-user.dto.ts
  BE/src/user/dto/update-user.dto.ts
  BE/src/user/entities/user-quiz-archive.entity.ts
  BE/src/user/entities/user.entity.ts
  BE/src/user/user.controller.spec.ts
  BE/src/user/user.controller.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.spec.ts
  BE/src/user/user.service.ts
Labels: 6. 퀴즈셋 생성 구현

#194 [BE] feat#192 Redis로 마이그레이션
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/constants/exception-message.ts
  BE/src/common/constants/redis-key.constant.ts
  BE/src/common/exceptions/game.ws.exception.ts
  BE/src/common/filters/ws-exception.filter.ts
  BE/src/common/utils/utils.spec.ts
  BE/src/common/utils/utils.ts
  BE/src/game/decorators/validate-room.decorator.ts
  BE/src/game/dto/create-game.dto.ts
  BE/src/game/game.gateway.spec.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/validations/game-validation.pipe.ts
  BE/src/game/validations/game.validator.ts
  BE/src/repository/RedisClient.ts
  BE/test/app.e2e-spec.ts
  BE/test/game.e2e-spec.ts
Labels: 1. 게임방 구현

#195 [FE] #143-148 게임 진행 관련 기능 구현 및 잔버그 수정
  FE/package-lock.json
  FE/package.json
  FE/src/api/socketEventTypes.ts
  FE/src/assets/lottie/answer_background.json
  FE/src/assets/lottie/answer_effect.json
  FE/src/assets/lottie/character.json
  FE/src/assets/lottie/fail_effect.json
  FE/src/assets/lottie/fail_effect2.json
  FE/src/assets/lottie/success_effect2.json
  FE/src/components/AnswerModal.tsx
  FE/src/components/Chat.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/ParticipantDisplay.tsx
  FE/src/components/Player.tsx
  FE/src/components/QuizHeader.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/components/QuizPreview.tsx
  FE/src/components/QuizSettingModal.tsx
  FE/src/constants/gameState.ts
  FE/src/pages/GamePage.tsx
  FE/src/pages/GameSetupPage.tsx
  FE/src/store/useChatStore.ts
  FE/src/store/usePlayerStore.ts
  FE/src/store/useQuizStore.ts
  FE/src/store/useRoomStore.ts
Labels: 2. 진행방 구현

#193 [BE] feat#48#51#52 게임방 옵션 및 퀴즈셋 변경 이벤트 처리 구현
  BE/src/game/dto/update-room-option.dto.ts
  BE/src/game/dto/update-room-quizset.dto.ts
  BE/src/game/game.gateway.ts
Labels: 3. 대기방 구현

#199 [FE] feat#198 프론트 mocking 설정 후 게임 진행 테스트
  FE/src/api/mocks/SocketMock.ts
  FE/src/api/mocks/socketMocks/SocketMockChat.ts
  FE/src/api/mocks/socketMocks/SocketMockStartGame.ts
  FE/src/api/mocks/socketMocks/index.ts
  FE/src/api/socket.ts
  FE/src/api/socketEventTypes.ts
  FE/src/components/Player.tsx
  FE/src/components/QuizHeader.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/constants/quizState.ts
  FE/src/pages/GamePage.tsx
  FE/src/store/usePlayerStore.ts
  FE/src/store/useQuizStore.ts
Labels: 2. 진행방 구현

#197 [BE] feat#47#179 퀴즈셋 cud 구현, test code 작성
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/quiz/dto/create-quiz.dto.ts
  BE/src/quiz/dto/update-quiz.dto.ts
  BE/src/quiz/quiz.controller.ts
  BE/src/quiz/quiz.service.spec.ts
  BE/src/quiz/quiz.service.ts
  BE/test/quiz.e2e-spec.ts
Labels: 6. 퀴즈셋 생성 구현

#201 [BE] feat#200 깃헙액션에서 mysql을 이용한 test 구현 (자동배포)
  .github/workflows/deploy.yml
  .github/workflows/notify-pr-review.yml
  BE/src/app.module.ts
  BE/src/quiz/quiz.controller.spec.ts
  BE/test/app.e2e-spec.ts
  BE/test/quiz.e2e-spec.ts
Labels: 0. 개발 환경 세팅

#196 [BE] feat#53#57 게임 시작 및 진행 구현, 기존 구현들 다중 서버 고려
  BE/.jest-test-results.json
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/constants/exception-message.ts
  BE/src/common/constants/redis-key.constant.ts
  BE/src/common/constants/socket-events.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/service/game.chat.service.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/game/validations/game.validator.ts
  BE/test/game.e2e-spec.ts
  BE/test/mocks/custom-redis.mock.ts
  BE/test/mocks/quiz-data.mock.ts
Labels: 2. 진행방 구현, 3. 대기방 구현

#203 [FE] feat#198 게임 상황 전반 모킹
  FE/package-lock.json
  FE/package.json
  FE/src/api/mocks/SocketMock.ts
  FE/src/api/mocks/socketMocks/SocketMockChat.ts
  FE/src/api/mocks/socketMocks/SocketMockLoadTest.ts
  FE/src/api/mocks/socketMocks/SocketMockLoadTestWithQuiz.ts
  FE/src/api/mocks/socketMocks/SocketMockNextQuiz.ts
  FE/src/api/mocks/socketMocks/SocketMockStartGame.ts
  FE/src/api/mocks/socketMocks/index.ts
  FE/src/api/socketEventTypes.ts
  FE/src/assets/lottie/answer_background.json
  FE/src/assets/lottie/answer_effect.json
  FE/src/assets/lottie/character.json
  FE/src/assets/lottie/character3.json
  FE/src/assets/lottie/fail_effect2.json
  FE/src/assets/lottie/quiz_loading.json
  FE/src/components/AnswerModal.tsx
  FE/src/components/Chat.tsx
  FE/src/components/GameHeader.tsx
  FE/src/components/Player.tsx
  FE/src/components/QuizHeader.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/components/QuizPreview.tsx
  FE/src/constants/quizState.ts
  FE/src/pages/GamePage.tsx
  FE/src/store/useQuizStore.ts
  FE/tailwind.config.js
Labels: 1. 게임방 구현

#209 [FE] feat#46 선택한 퀴즈셋 서버로 전송
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/api/mocks/SocketMock.ts
  FE/src/api/mocks/socketMocks/SocketMockStartGame.ts
  FE/src/api/socketEventTypes.ts
  FE/src/components/QuizHeader.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/components/QuizPreview.tsx
  FE/src/components/QuizSetSearchList.tsx
  FE/src/components/QuizSettingModal.tsx
  FE/src/hooks/useServerDate.ts
  FE/src/main.tsx
  FE/src/mocks/browser.ts
  FE/src/mocks/data.ts
  FE/src/mocks/handlers.ts
Labels: 3. 대기방 구현

#212 [FE] feat#210-211 퀴즈 결과창 및 대기방 목록 페이지
  FE/src/App.tsx
  FE/src/api/mocks/socketMocks/SocketMockStartEnd.ts
  FE/src/api/mocks/socketMocks/index.ts
  FE/src/api/socketEventTypes.ts
  FE/src/assets/lottie/star_bg.json
  FE/src/assets/lottie/trophy.json
  FE/src/components/HeaderBar.tsx
  FE/src/components/LobbyList.tsx
  FE/src/components/ResultModal.tsx
  FE/src/constants/gameState.ts
  FE/src/pages/GameLobbyPage.tsx
  FE/src/pages/GamePage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/store/useRoomStore.ts
Labels: 2. 진행방 구현, 3. 대기방 구현

#208 [BE] feat#206#207 대기방 목록 조회 API 구현 및 기존 API들 리팩토링
  BE/package-lock.json
  BE/package.json
  BE/src/InitDB/InitDB.Service.ts
  BE/src/InitDB/InitDB.module.ts
  BE/src/app.module.ts
  BE/src/game/service/game.service.ts
  BE/src/quiz-set/dto/create-quiz.dto.ts
  BE/src/quiz-set/dto/quiz-set-list-response.dto.ts
  BE/src/quiz-set/dto/update-quiz.dto.ts
  BE/src/quiz-set/entities/quiz-choice.entity.ts
  BE/src/quiz-set/entities/quiz-set.entity.ts
  BE/src/quiz-set/entities/quiz.entity.ts
  BE/src/quiz-set/quiz-set.controller.ts
  BE/src/quiz-set/quiz-set.module.ts
  BE/src/quiz-set/service/quiz-set-create.service.ts
  BE/src/quiz-set/service/quiz-set-delete.service.ts
  BE/src/quiz-set/service/quiz-set-read.service.ts
  BE/src/quiz-set/service/quiz-set-update.service.ts
  BE/src/quiz-set/service/quiz-set.service.ts
  BE/src/quiz/dto/Response.dto.ts
  BE/src/quiz/quiz.module.ts
  BE/src/quiz/quiz.service.spec.ts
  BE/src/quiz/quiz.service.ts
  BE/src/user/entities/user-quiz-archive.entity.ts
  BE/src/user/entities/user.entity.ts
  BE/src/waiting-room/dto/waiting-room-list.response.dto.ts
  BE/src/waiting-room/entities/waiting-room.entity.ts
  BE/src/waiting-room/waiting-room.controller.ts
  BE/src/waiting-room/waiting-room.module.ts
  BE/src/waiting-room/waiting-room.service.spec.ts
  BE/src/waiting-room/waiting-room.service.ts
  BE/test/integration/game.integration.spec.ts
  BE/test/integration/quiz.integration.spec.ts
  BE/test/jest-integration.json
  BE/test/mocks/custom-redis.mock.ts
Labels: 3. 대기방 구현

#213 [BE] feat#205 실제 퀴즈셋 가져오기
  BE/src/common/constants/redis-key.constant.ts
  BE/src/game/game.module.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/game/service/quiz.cache.service.ts
  BE/test/integration/game.integration.spec.ts
  BE/test/mocks/quiz-data.mock.ts
Labels: 2. 진행방 구현

#223 [FE] feat#27#221#222 서바이벌 모드 구현 및 게임 종료 후 호스트 변경 구현
  FE/src/api/mocks/SocketMock.ts
  FE/src/api/mocks/socketMocks/SocketMockChat.ts
  FE/src/api/mocks/socketMocks/SocketMockLoadTest.ts
  FE/src/api/mocks/socketMocks/SocketMockLoadTestWithQuiz.ts
  FE/src/api/mocks/socketMocks/SocketMockNextQuiz.ts
  FE/src/api/mocks/socketMocks/SocketMockStartEnd.ts
  FE/src/api/mocks/socketMocks/SocketMockStartGame.ts
  FE/src/components/ParticipantDisplay.tsx
  FE/src/components/Player.tsx
  FE/src/components/QuizHeader.tsx
  FE/src/components/QuizOptionBoard.tsx
  FE/src/components/QuizSetSearchList.tsx
  FE/src/components/QuizSettingModal.tsx
  FE/src/components/ResultModal.tsx
  FE/src/hooks/useServerDate.ts
  FE/src/mocks/data.ts
  FE/src/pages/GameLobbyPage.tsx
  FE/src/pages/GamePage.tsx
  FE/src/store/usePlayerStore.ts
  FE/src/store/useQuizStore.ts
  FE/src/utils/serverTime.ts
Labels: 1. 게임방 구현, 2. 진행방 구현

#225 [FE] feat#76#84#224 로그인/회원가입, 마이페이지 ui, 채팅 스크롤 개선
  FE/src/App.tsx
  FE/src/components/Chat.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/QuizSetupPage.tsx
Labels: 1. 게임방 구현, 7. 인증과 인가 구현, 8. 마이페이지 구현

#220 [BE] feat#219#219 게임진행예외처리, redis구독 리팩토링
  BE/src/common/constants/exception-message.ts
  BE/src/common/filters/ws-exception.filter.ts
  BE/src/common/redis/redis-subscriber.service.ts
  BE/src/common/redis/subscribers/base.subscriber.ts
  BE/src/common/redis/subscribers/player.subscriber.ts
  BE/src/common/redis/subscribers/room.subscriber.ts
  BE/src/common/redis/subscribers/scoring.subscriber.ts
  BE/src/common/redis/subscribers/timer.subscriber.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/game/service/quiz.cache.service.ts
  BE/src/game/validations/game.validator.ts
  BE/src/quiz-set/quiz-set.module.ts
  BE/test/integration/game.integration.spec.ts
Labels: 2. 진행방 구현

#226 [BE] feat#74#77 회원가입, 로그인 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/auth/auth.controller.spec.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.spec.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/signup.dto.ts
  BE/src/auth/guard/jwt-auth.guard.ts
  BE/src/auth/guard/jwt.strategy.ts
  BE/src/auth/guard/local-auth.guard.ts
  BE/src/auth/guard/local.strategy.ts
  BE/src/user/dto/create-user.dto.ts
  BE/src/user/dto/update-user.dto.ts
  BE/src/user/user.controller.spec.ts
  BE/src/user/user.controller.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: 7. 인증과 인가 구현

#217 [BE] feat#215#216 서버 시간 조회 API 추가, 퀴즈 목록 조회 API 수정
  BE/src/app.module.ts
  BE/src/main.ts
  BE/src/quiz-set/dto/quiz-set-list-response.dto.ts
  BE/src/quiz-set/service/quiz-set-read.service.ts
  BE/src/time/time.controller.spec.ts
  BE/src/time/time.controller.ts
  BE/src/time/time.module.ts
  BE/test/integration/game.integration.spec.ts
  BE/test/integration/quiz.integration.spec.ts
Labels: 3. 대기방 구현

#232 [BE] feat#230 퀴즈셋 목록 조회, 대기방 목록 조회 API 커서 기반 페이징 구현
  BE/src/quiz-set/dto/quiz-set-list-response.dto.ts
  BE/src/quiz-set/quiz-set.controller.ts
  BE/src/quiz-set/service/quiz-set-read.service.ts
  BE/src/quiz-set/service/quiz-set.service.ts
  BE/src/waiting-room/dto/waiting-room-list.response.dto.ts
  BE/src/waiting-room/waiting-room.controller.ts
  BE/src/waiting-room/waiting-room.service.spec.ts
  BE/src/waiting-room/waiting-room.service.ts
  BE/test/integration/quiz.integration.spec.ts
Labels: 3. 대기방 구현

#236 [BE] feat#219 redis 메모리 관리 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/game/interceptor/gameActivity.interceptor.ts
  BE/src/game/redis/game-redis-memory.service.ts
  BE/src/game/redis/redis-subscriber.service.ts
  BE/src/game/redis/subscribers/base.subscriber.ts
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/redis/subscribers/room.cleanup.subscriber.ts
  BE/src/game/redis/subscribers/room.subscriber.ts
  BE/src/game/redis/subscribers/scoring.subscriber.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/game/service/quiz.cache.service.ts
  BE/src/main.ts
  BE/test/integration/game.integration.spec.ts
Labels: 2. 진행방 구현

#235 [BE] feat#227#228 퀴즈셋 기능에 유저 확인 추가, 게임 join 에 유저 확인 추가
  BE/src/InitDB/InitDB.Service.ts
  BE/src/app.module.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/decorators/current-user.decorator.ts
  BE/src/auth/guard/jwt.strategy.ts
  BE/src/auth/guard/ws-jwt-auth.guard.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
  BE/src/quiz-set/entities/quiz-set.entity.ts
  BE/src/quiz-set/quiz-set.controller.ts
  BE/src/quiz-set/quiz-set.module.ts
  BE/src/quiz-set/service/quiz-set-create.service.ts
  BE/src/quiz-set/service/quiz-set-delete.service.ts
  BE/src/quiz-set/service/quiz-set-update.service.ts
  BE/src/quiz-set/service/quiz-set.service.ts
  BE/test/integration/game.integration.spec.ts
  BE/test/integration/quiz.integration.spec.ts
Labels: 3. 대기방 구현, 6. 퀴즈셋 생성 구현

#240 [BE] fix#239 멀티프로세스로 실행시 endQuizTime이 발생 안 되는 이슈 해결
  BE/src/common/constants/redis-key.constant.ts
  BE/src/game/redis/subscribers/scoring.subscriber.ts
  BE/src/game/service/game.service.ts
Labels: 2. 진행방 구현

#243 [BE] feat#241 자동배포 수정
  .github/workflows/deploy.yml
  BE/src/game/interceptor/gameActivity.interceptor.ts
  BE/test/integration/game.integration.spec.ts
Labels: 0. 개발 환경 세팅

#242 [BE] test#238 테스트 코드 오류 수정
  BE/test/integration/quiz.integration.spec.ts
Labels: 6. 퀴즈셋 생성 구현

#247 [BE] hotfix#1
  .github/workflows/deploy.yml
  BE/ecosystem.config.js
  BE/src/auth/auth.controller.spec.ts
  BE/src/auth/auth.service.spec.ts
  BE/src/game/dto/create-game.dto.ts
  BE/src/game/dto/update-room-option.dto.ts
  BE/src/game/game.gateway.ts
  BE/src/game/redis/subscribers/room.subscriber.ts
  BE/src/game/service/game.room.service.ts
  BE/src/user/user.service.spec.ts
  BE/test/integration/game.integration.spec.ts
Labels: bug

#266 [FE] feat#30 강퇴 기능 구현 및 채팅렌더링 최적화
  FE/src/api/socket/socket.ts
  FE/src/api/socket/socketEventTypes.ts
  FE/src/constants/socketEvents.ts
  FE/src/features/game/components/GameHeader.tsx
  FE/src/features/game/components/ParticipantDisplay.tsx
  FE/src/features/game/data/socketListener.ts
Labels: 3. 대기방 구현

#267 [BE] feat#263 강퇴구현, 모니터링 도입
  BE/.eslintrc.js
  BE/package-lock.json
  BE/package.json
  BE/src/common/constants/exception-message.ts
  BE/src/common/constants/socket-events.ts
  BE/src/game/dto/kick-room.dto.ts
  BE/src/game/game.gateway.ts
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/validations/game.validator.ts
  BE/src/main.ts
Labels: 3. 대기방 구현

#268 [BE] feat#264 서바이벌 모드 구현 및 테스트 코드 개선
  BE/src/common/constants/game-mode.ts
  BE/src/common/filters/ws-exception.filter.ts
  BE/src/game/dto/create-game.dto.ts
  BE/src/game/dto/update-room-option.dto.ts
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/redis/subscribers/scoring.subscriber.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.chat.service.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/user/entities/user-quiz-archive.entity.ts
  BE/test/integration/game.integration.spec.ts
  BE/test/integration/game/game-chat.integratoin.spec.ts
  BE/test/integration/game/game-room.integration.spec.ts
  BE/test/integration/game/game-survival.integration.spec.ts
  BE/test/integration/game/game.integration.spec.ts
  BE/test/integration/quiz-set/quiz.integration.spec.ts
  BE/test/integration/setup/game.setup.ts
  BE/test/integration/setup/socket.helper.ts
  BE/test/integration/setup/util.ts
Labels: 1. 게임방 구현

#270 [BE] feat#229 모니터링 인터셉터 구현
  BE/src/common/interceptor/SocketEventLoggerInterceptor.ts
  BE/src/game/game.gateway.ts
  BE/src/game/service/game.chat.service.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/src/game/service/quiz.cache.service.ts
Labels: 0. 개발 환경 세팅

#265 [BE] feat#261 재접속 기능 구현
  BE/package-lock.json
  BE/package.json
  BE/src/common/constants/redis-key.constant.ts
  BE/src/common/constants/socket-events.ts
  BE/src/common/utils/utils.ts
  BE/src/game/dto/set-player-name.dto.ts
  BE/src/game/game.gateway.ts
  BE/src/game/redis/redis-subscriber.service.ts
  BE/src/game/redis/subscribers/base.subscriber.ts
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/redis/subscribers/room.cleanup.subscriber.ts
  BE/src/game/redis/subscribers/room.subscriber.ts
  BE/src/game/redis/subscribers/scoring.subscriber.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.chat.service.ts
  BE/src/game/service/game.room.service.ts
  BE/src/game/service/game.service.ts
  BE/test/integration/game/game-chat.integratoin.spec.ts
  BE/test/integration/game/game-room.integration.spec.ts
  BE/test/integration/game/game-survival.integration.spec.ts
  BE/test/integration/game/game.integration.spec.ts
  BE/test/integration/setup/socket.helper.ts
Labels: 2. 진행방 구현

#271 [BE] feat#229 모니터링 구현 v4
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/CommonModule.ts
  BE/src/common/interceptor/SocketEventLoggerInterceptor.ts
  BE/src/common/service/SystemMetricsService.ts
  BE/src/game/game.gateway.ts
  BE/src/game/game.module.ts
Labels: 0. 개발 환경 세팅

#277 [BE] fix#275#276 소켓연결할때 error 발생시 서버가 죽는버그
  BE/src/common/constants/exception-message.ts
  BE/src/game/game.gateway.ts
Labels: bug

#282 [BE] feat#281 카테고리 enum 설정
  BE/src/quiz-set/entities/quiz-set.entity.ts
  BE/src/quiz-set/quiz-set.controller.ts
  BE/src/quiz-set/service/quiz-set-create.service.ts
Labels: 6. 퀴즈셋 생성 구현

#280 [BE] fix# 새 호스트 설정 및 이벤트 전송 추가
  BE/src/common/constants/socket-events.ts
  BE/src/game/redis/subscribers/room.subscriber.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.room.service.ts
Labels: bug

#288 [BE] fix: [BE] 강퇴시 kickRoom event 발송, 선택지 동적결정, joinRoom시 host여부 전송
  .github/workflows/deploy.yml
  BE/src/game/redis/subscribers/player.subscriber.ts
  BE/src/game/redis/subscribers/timer.subscriber.ts
  BE/src/game/service/game.room.service.ts
  README.md
Labels: bug

#289 [BE] fix: CORS Origin 설정 및 쿠키 SameSite, Secure 옵션 추가
  BE/src/game/game.gateway.ts
Labels: bug
